### ISSUE TITLE
Link to model files broken

### ISSUE THREAD

**Issue by mgrewe** [guanhuankang/ShadowDetection2021#1]
Hi @guanhuankang 

thanks for publishing your interesting work. I wanted to check it out, but it seems that the download links are broken. Would be great it this could be fixed.

Thanks and Regards
Martin

**Comment by guanhuankang** [comment]
Hi Martin,

Thank you for your attention! We have updated the links for the checkpoint files. You can download the checkpoints now.

Best,
Huankang Guan

**Comment by mgrewe** [comment]
Hi @guanhuankang Works now, thanks for the quick fix. Highly appreciated!
